version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ti-mo/conntracct
