bpf/* {
  prep: go tool mage bpf:build
}

**/*_test.go {
  prep +onchange: go test @dirmods
}

**/*.go {
  prep +onchange: golangci-lint run @dirmods
  prep: go tool mage build
  daemon +sigterm: ./build/conntracct -d run -c configs/default.yml
}
