// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type acctCurvePoint struct {
	_        structs.HostLayout
	Age      uint64
	Interval uint64
}

type acctEvent struct {
	_       structs.HostLayout
	Type    uint32
	_       [4]byte
	Start   uint64
	Ts      uint64
	Srcaddr struct {
		_   structs.HostLayout
		In6 struct {
			_    structs.HostLayout
			In6U struct {
				_       structs.HostLayout
				U6Addr8 [16]uint8
			}
		}
	}
	Dstaddr struct {
		_   structs.HostLayout
		In6 struct {
			_    structs.HostLayout
			In6U struct {
				_       structs.HostLayout
				U6Addr8 [16]uint8
			}
		}
	}
	PacketsOrig uint64
	BytesOrig   uint64
	PacketsRet  uint64
	BytesRet    uint64
	Connmark    uint32
	Netns       uint32
	Srcport     uint16
	Dstport     uint16
	Proto       uint8
	_           [3]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	acctMapFlowCooldown = "flow_cooldown"
	acctMapFlowOrigin   = "flow_origin"
	acctMapRingbuf      = "ringbuf"
	acctProgCtDestroy   = "ct_destroy"
	acctProgCtNew       = "ct_new"
	acctProgCtUpdate    = "ct_update"
	acctVarCurve0       = "curve0"
	acctVarCurve1       = "curve1"
	acctVarCurve2       = "curve2"
)

// loadAcct returns the embedded CollectionSpec for acct.
func loadAcct() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AcctBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load acct: %w", err)
	}

	return spec, err
}

// loadAcctObjects loads acct and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*acctObjects
//	*acctPrograms
//	*acctMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAcctObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAcct()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// acctSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctSpecs struct {
	acctProgramSpecs
	acctMapSpecs
	acctVariableSpecs
}

// acctProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctProgramSpecs struct {
	CtDestroy *ebpf.ProgramSpec `ebpf:"ct_destroy"`
	CtNew     *ebpf.ProgramSpec `ebpf:"ct_new"`
	CtUpdate  *ebpf.ProgramSpec `ebpf:"ct_update"`
}

// acctMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctMapSpecs struct {
	FlowCooldown *ebpf.MapSpec `ebpf:"flow_cooldown"`
	FlowOrigin   *ebpf.MapSpec `ebpf:"flow_origin"`
	Ringbuf      *ebpf.MapSpec `ebpf:"ringbuf"`
}

// acctVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctVariableSpecs struct {
	Curve0 *ebpf.VariableSpec `ebpf:"curve0"`
	Curve1 *ebpf.VariableSpec `ebpf:"curve1"`
	Curve2 *ebpf.VariableSpec `ebpf:"curve2"`
}

// acctObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctObjects struct {
	acctPrograms
	acctMaps
	acctVariables
}

func (o *acctObjects) Close() error {
	return _AcctClose(
		&o.acctPrograms,
		&o.acctMaps,
	)
}

// acctMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctMaps struct {
	FlowCooldown *ebpf.Map `ebpf:"flow_cooldown"`
	FlowOrigin   *ebpf.Map `ebpf:"flow_origin"`
	Ringbuf      *ebpf.Map `ebpf:"ringbuf"`
}

func (m *acctMaps) Close() error {
	return _AcctClose(
		m.FlowCooldown,
		m.FlowOrigin,
		m.Ringbuf,
	)
}

// acctVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctVariables struct {
	Curve0 *ebpf.Variable `ebpf:"curve0"`
	Curve1 *ebpf.Variable `ebpf:"curve1"`
	Curve2 *ebpf.Variable `ebpf:"curve2"`
}

// acctPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctPrograms struct {
	CtDestroy *ebpf.Program `ebpf:"ct_destroy"`
	CtNew     *ebpf.Program `ebpf:"ct_new"`
	CtUpdate  *ebpf.Program `ebpf:"ct_update"`
}

func (p *acctPrograms) Close() error {
	return _AcctClose(
		p.CtDestroy,
		p.CtNew,
		p.CtUpdate,
	)
}

func _AcctClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed acct_arm64_bpfel.o
var _AcctBytes []byte
