// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type acctEventT struct {
	_       structs.HostLayout
	Start   uint64
	Ts      uint64
	Cptr    uint64
	Srcaddr struct {
		_   structs.HostLayout
		All [4]uint32
	}
	Dstaddr struct {
		_   structs.HostLayout
		All [4]uint32
	}
	PacketsOrig uint64
	BytesOrig   uint64
	PacketsRet  uint64
	BytesRet    uint64
	Connmark    uint32
	Netns       uint32
	Srcport     uint16
	Dstport     uint16
	Proto       uint8
	_           [3]byte
}

type acctO_config uint32

const (
	acctO_configConfigReady acctO_config = 0
	acctO_configConfigMax   acctO_config = 1
)

type acctO_configRatecurve uint32

const (
	acctO_configRatecurveConfigCurve0Age      acctO_configRatecurve = 0
	acctO_configRatecurveConfigCurve0Interval acctO_configRatecurve = 1
	acctO_configRatecurveConfigCurve1Age      acctO_configRatecurve = 2
	acctO_configRatecurveConfigCurve1Interval acctO_configRatecurve = 3
	acctO_configRatecurveConfigCurve2Age      acctO_configRatecurve = 4
	acctO_configRatecurveConfigCurve2Interval acctO_configRatecurve = 5
	acctO_configRatecurveConfigCurveMax       acctO_configRatecurve = 6
)

// loadAcct returns the embedded CollectionSpec for acct.
func loadAcct() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AcctBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load acct: %w", err)
	}

	return spec, err
}

// loadAcctObjects loads acct and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*acctObjects
//	*acctPrograms
//	*acctMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAcctObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAcct()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// acctSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctSpecs struct {
	acctProgramSpecs
	acctMapSpecs
	acctVariableSpecs
}

// acctProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctProgramSpecs struct {
	KprobeNfConntrackHashInsert *ebpf.ProgramSpec `ebpf:"kprobe____nf_conntrack_hash_insert"`
	KprobeNfCtRefreshAcct       *ebpf.ProgramSpec `ebpf:"kprobe____nf_ct_refresh_acct"`
	KprobeNfCtDelete            *ebpf.ProgramSpec `ebpf:"kprobe__nf_ct_delete"`
	KretprobeNfCtRefreshAcct    *ebpf.ProgramSpec `ebpf:"kretprobe____nf_ct_refresh_acct"`
}

// acctMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctMapSpecs struct {
	Config          *ebpf.MapSpec `ebpf:"config"`
	ConfigRatecurve *ebpf.MapSpec `ebpf:"config_ratecurve"`
	Currct          *ebpf.MapSpec `ebpf:"currct"`
	FlowCooldown    *ebpf.MapSpec `ebpf:"flow_cooldown"`
	FlowOrigin      *ebpf.MapSpec `ebpf:"flow_origin"`
	PerfAcctEnd     *ebpf.MapSpec `ebpf:"perf_acct_end"`
	PerfAcctUpdate  *ebpf.MapSpec `ebpf:"perf_acct_update"`
}

// acctVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type acctVariableSpecs struct {
	ReadyVal *ebpf.VariableSpec `ebpf:"ready_val"`
}

// acctObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctObjects struct {
	acctPrograms
	acctMaps
	acctVariables
}

func (o *acctObjects) Close() error {
	return _AcctClose(
		&o.acctPrograms,
		&o.acctMaps,
	)
}

// acctMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctMaps struct {
	Config          *ebpf.Map `ebpf:"config"`
	ConfigRatecurve *ebpf.Map `ebpf:"config_ratecurve"`
	Currct          *ebpf.Map `ebpf:"currct"`
	FlowCooldown    *ebpf.Map `ebpf:"flow_cooldown"`
	FlowOrigin      *ebpf.Map `ebpf:"flow_origin"`
	PerfAcctEnd     *ebpf.Map `ebpf:"perf_acct_end"`
	PerfAcctUpdate  *ebpf.Map `ebpf:"perf_acct_update"`
}

func (m *acctMaps) Close() error {
	return _AcctClose(
		m.Config,
		m.ConfigRatecurve,
		m.Currct,
		m.FlowCooldown,
		m.FlowOrigin,
		m.PerfAcctEnd,
		m.PerfAcctUpdate,
	)
}

// acctVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctVariables struct {
	ReadyVal *ebpf.Variable `ebpf:"ready_val"`
}

// acctPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAcctObjects or ebpf.CollectionSpec.LoadAndAssign.
type acctPrograms struct {
	KprobeNfConntrackHashInsert *ebpf.Program `ebpf:"kprobe____nf_conntrack_hash_insert"`
	KprobeNfCtRefreshAcct       *ebpf.Program `ebpf:"kprobe____nf_ct_refresh_acct"`
	KprobeNfCtDelete            *ebpf.Program `ebpf:"kprobe__nf_ct_delete"`
	KretprobeNfCtRefreshAcct    *ebpf.Program `ebpf:"kretprobe____nf_ct_refresh_acct"`
}

func (p *acctPrograms) Close() error {
	return _AcctClose(
		p.KprobeNfConntrackHashInsert,
		p.KprobeNfCtRefreshAcct,
		p.KprobeNfCtDelete,
		p.KretprobeNfCtRefreshAcct,
	)
}

func _AcctClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed acct_arm64_bpfel.o
var _AcctBytes []byte
