// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package bpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[New-1]
	_ = x[Update-2]
	_ = x[Destroy-4]
}

const (
	_EventType_name_0 = "NewUpdate"
	_EventType_name_1 = "Destroy"
)

var (
	_EventType_index_0 = [...]uint8{0, 3, 9}
)

func (i EventType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case i == 4:
		return _EventType_name_1
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
